import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/regions";

/**
 * Replaces the legacy robots.txt files, which were generated by seoptimer.com,
 * identical across all three sites, and — like the sitemaps — never actually
 * served because they lived in src/app/ rather than public/.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{ userAgent: "*", allow: "/" }],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
